### ISSUE TITLE
继续汉化@Test

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/junit4_in_chinese#1]
@azige 的一个方案在 https://github.com/program-in-chinese/overview/issues/10#issuecomment-320610037
请问有空提交一下吗? 把CustomRunner也汉化如何?

**Comment by azige** [comment]
于是问题来了，应该给这个Runner起个什么名字？

**Comment by nobodxbodon** [comment]
运行器?

**Comment by nobodxbodon** [comment]
https://github.com/program-in-chinese/junit4_in_chinese/pull/2
